### ISSUE TITLE
Sourcemaps don't work

### ISSUE THREAD

**Issue by ramlmn** [Polymer/polymer-bundler#516]
I was trying to write my own build build script instead of using `polymer bundle`. So I wrote something that looks like this ...
``` js
const parse5 = require('parse5');
const {Bundler} = require('polymer-bundler');

const bundler = new Bundler({
  sourcemaps: true,
});

bundler.generateManifest(['index.html']).then((manifest) => {
  bundler.bundle(manifest).then((result) => {
    const parsedHtml = parse5.serialize(result.documents.get('index.html').ast);
    // ...
  }).catch(console.error);
}).catch(console.error);
```
... as specified in the docs.

But it outputs an error something like this
```
Error: Invalid mapping: {"generated":{"line":2,"column":0},"source":null,"original":{"line":null,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/mnt/d/web/testing/sandboxes/polymer/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/mnt/d/web/testing/sandboxes/polymer/node_modules/source-map/lib/source-map-generator.js:101:12)
    at consumer.eachMapping.mapping (/mnt/d/web/testing/sandboxes/polymer/node_modules/polymer-bundler/lib/source-map.js:84:19)
    at Array.forEach (native)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/mnt/d/web/testing/sandboxes/polymer/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at offsetSourceMap (/mnt/d/web/testing/sandboxes/polymer/node_modules/polymer-bundler/lib/source-map.js:71:14)
    at Object.<anonymous> (/mnt/d/web/testing/sandboxes/polymer/node_modules/polymer-bundler/lib/source-map.js:141:25)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/d/web/testing/sandboxes/polymer/node_modules/polymer-bundler/lib/source-map.js:17:58)
```

If the `sourcemaps` options is either set to `false` or removed completely, everything works fine. And there is not enough documentation on how to extract generated sourcemap from the `result` object.

Is this a bug, or is there something I am missing, please let me know.

**Comment by Lange** [comment]
I am having a similar issue where I receive an `Invalid mapping` error: 
```
(node:36360) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: Invalid mapping: {"generated":{"line":2,"column":9355},"source":null,"original":{"line":null,"column":null},"name":null}
```

**Comment by Lange** [comment]
Follow-up to my edits above: I've fixed my gulpfile such that I'm only generating source maps for the files I want to, and I'm still getting the same issue. Even if I narrow it down such that I'm only generating a source map for a single file, I get this problem -- it doesn't matter what file I choose.

**Comment by ramlmn** [comment]
But I am not doing anything with my source files. I am just telling `polymer-bundler` to just generate a manifest (gather all its dependencies). I would later then bundle and pass it to babel or uglify or something else.

I've used chrome debugging to inspect the code and the promise rejected is of the `generateManifest`.

**Comment by Lange** [comment]
This might be the cause of this error? https://github.com/mozilla/source-map/issues/263

**Comment by Lange** [comment]
@ramlmn Can you try with this pull request? https://github.com/Polymer/polymer-bundler/pull/519

**Comment by ramlmn** [comment]
@Lange That works!
