### ISSUE TITLE
vulcanise 1.16.0 complains about missing nopt dep

### ISSUE THREAD

**Issue by paladox** [Polymer/polymer-bundler#597]
Hi i am trying to upgrade to vulcanise 1.16.0 from 1.14.8 but seem to be getting stuck on it failing with

module.js:487
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/tmp/_bazel_x/4e4bb427cd475349ab3944ff29048468/execroot/gerrit/external/vulcanize/vulcanize@1.16.0-b0ce3b0044d194ad4908ae4f1a6c6110a6e4d5e6/package/bin/vulcanize:15:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by usergenic** [comment]
@paladox does this issue still affect you?  does any specific invocation give you this error or does this happen regardless of what arguments you give to `vulcanize`.   for example, does `vulcanize -h` show you help?

**Comment by paladox** [comment]
Nope, it works now. I believe the issue is because in gerrit vulcanise is built and uploaded to ne of gerrit servers with all the deps built.
