### ISSUE TITLE
Figure out how to handle import.meta.url

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-bundler#624]
If a module is using `import.meta.url` to load a resource and it's included in a bundle in a different location, the value of `import.meta.url` will be wrong. It seems like the bundler needs to rewrite `import.meta.url`.

This implies that either:
  1. Patterns where modules pass around the `import.meta` object for other libraries to read properties off of needs to be discouraged, or
  2. We need to figure out a way to rewrite `import.meta` into an object that proxies `import.meta` while overwriting the `url` property.

cc @rictic for potential linter rule if we choose option 1.

**Comment by justinfagnani** [comment]
Main use case:

```js
class FunkyImage extends PolymerElement {
  static importPath = import.meta.url;
  static template = html`<img src="./funky.jpg>"`;
}
```

When bundled, we want Polymer to be able to rewrite the `src` attribute using `importPath`.

If we do option 2, the output would look something like:

```js
class FunkyImage extends PolymerElement {
  static importPath = {url: '/root/elements/funky-image.js'}.url;
  static template = html`<img src="./funky.jpg>"`;
}
```

**Comment by web-padawan** [comment]
Has this been implemented yet?
I have tried bundling the project with the `import.meta.url` present in one component, and I had the following error: 
```sh
error:   Promise rejection: Error: Unexpected token
error:   Error: Unexpected token
    at error (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:168:15)
    at Module.error (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:19072:9)
    at tryParse (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:18763:16)
    at Module.setSource (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:18818:24)
    at /Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:21457:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

The relevant part of the `polymer.json` looks like this:
```js
  "builds": [
    {
      "bundle": true,
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      },
      "js": {
        "minify": false,
        "compile": false,
        "transformModulesToAmd": false
      }
    }
  ],
```

Then I commented the line and everything was bundled fine, after uncommenting it back I got the native `import.meta.url` working in Chrome with the bundled version.

The use case for us is basically to detect whether the app was bundled or not on the client side, in order to decide if we should perform some metrics-related code or not.

**Comment by web-padawan** [comment]
I'm still getting the error mentioned above with the CLI v1.7.0-pre.11 having import.meta transform implied by AMD transform, when bundling like this:
```sh
$ polymer build --entrypoint test.html --npm --module-resolution=node --js-transform-modules-to-amd --bundle --js-transform-import-meta
info: [cli.command.build]    Clearing build/ directory...
error: [cli.main]   Promise rejection: Error: Unexpected token
error: [cli.main]   Error: Unexpected token
    at error (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:168:15)
    at Module.error (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:19072:9)
    at tryParse (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:18763:16)
    at Module.setSource (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:18818:24)
    at /Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:21457:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
